rootDir: .
services:
  - type: web
    name: silifke-kurye
    runtime: php
    buildCommand: "composer install && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: DB_CONNECTION
        value: sqlite
      - key: CACHE_STORE
        value: file
      - key: DB_DATABASE
        value: /opt/render/project/src/storage/database.sqlite